### ISSUE TITLE
docs.rust-lang.org 404 search is broken

### ISSUE THREAD

**Issue by mb64** [rust-lang/www.rust-lang.org#864] opened 2019-06-06 02:14 UTC
(I'm not sure where to submit a bug report for doc.rust-lang.org; if there is a better place please correct me.)

On the 404 page for doc.rust-lang.org, the "Search the standard library" form directs to `std/...`, meaning that if the not found URL contains a slash, it will direct to the wrong site, and get another 404 page.

For example, on [https://doc.rust-lang.org/does-not-exist/](https://doc.rust-lang.org/does-not-exist/), the search button directs to [https://doc.rust-lang.org/does-not-exist/std/index.html?search=](https://doc.rust-lang.org/does-not-exist/std/index.html?search=).

The solution would be to edit the line `document.location.href = 'std/index.html?search=' + encodeURIComponent(q);` from `'std/...` to `'/std/...`.  I'm not sure what file this is in.

**Comment by Manishearth** [comment] 2019-06-06 02:14
Not the right repo, but it's fine

cc @rust-lang/docs

**Comment by steveklabnik** [comment] 2019-06-07 13:33
> I'm not sure what file this is in.

It's somewhere in https://github.com/rust-lang/rust/tree/master/src/librustdoc

**Comment by ollie27** [comment] 2019-06-07 17:42
The file is https://github.com/rust-lang/rust/blob/master/src/doc/not_found.md.

**Comment by QuietMisdreavus** [comment] 2019-06-10 16:27
Duplicate of https://github.com/rust-lang/rust/issues/54952. Also see discussion in https://github.com/rust-lang/rust/pull/55188, which tried to fix this but uncovered an issue with the approach.

The 404 page for doc.rust-lang.org is not handled by rustdoc - it's set by the site itself. As for team ownership, rustdoc team is fine, since it's interfacing with the search functionality of rustdoc output.

**Comment by Manishearth** [comment] 2019-06-10 17:12
closing as dupe

**Closed by Manishearth** 2019-06-10 17:12 UTC
