### ISSUE TITLE
Replace Fira with FiraGO

### ISSUE THREAD

**Issue by skade** [rust-lang/www.rust-lang.org#755] opened 2019-05-10 08:31 UTC
# Design Feature Request
## Summary
FiraGo is an extended version Fira with better support for non-latin fonts.

## Motivation
This might help in i18n efforts.

## Drawbacks
Potentially increased font file size.

**Comment by skade** [comment] 2019-06-02 15:00
Confirmed: Fira doesn't render characters necessary for the Turkish translation.

**Comment by skade** [comment] 2019-06-05 16:36
Wrong, Fira renders correctly, our headlines are in Alfa Sans, see #858

**Comment by XAMPPRocky** [comment] 2020-03-01 11:16
Closing as a duplicate of #867

**Closed by XAMPPRocky** 2020-03-01 11:16 UTC
Labels: A-Design
