### ISSUE TITLE
Use Noto Sans SC/TC in additional to Alfa Sans One on Chinese site (and choose suitable fonts for other scripts too)

### ISSUE THREAD

**Issue by kennytm** [rust-lang/www.rust-lang.org#875] opened 2019-06-10 21:12 UTC
# Design Feature Request
## Summary

Embed and use **Noto Sans SC** for the section header font in the Simplified Chinese site, and **Noto Sans TC** for the Traditional Chinese site.

## Motivation

Currently the header font is "Alfa Slab One", which is a slab-serif font. The header font fallbacks to the default "serif" font at weight = 300 (inherited from Skeleton). Since "Alfa Slab One" is a very heavy slab-serif font, this leads to some ugly typography on unsupported glyphs (anything not Latin).

![Screenshot 2019-06-11 at 04 18 36-fs8](https://user-images.githubusercontent.com/103023/59224501-224f7780-8c01-11e9-8939-e236b33a8f46.png)

One immediate improvement is change the header fallback font from "serif 300" to "sans-serif 900" so the contrast is more similar. However this will cause the English text even bolder as "Alfa Slab One"'s weight is "Regular (400)"! Also, even at the maximum weight "sans-serif 900" the built-in font may still not be heavy enough to fit with "Alfa Slab One".

Therefore, we should choose custom fonts which matches the weight and style of "Alfa Slab One" to make the title look better. 

For Chinese (both Simplified and Traditional), the free font with closest weight to "Alfa Slab One" is "[Source Han Sans (思源黑體)](https://en.wikipedia.org/wiki/Source_Han_Sans)" a.k.a. "Noto Sans CJK" at weight 900, as shown above.

## Drawbacks

* The custom font assets can be big for CJK fonts. The entire `NotoSansCJKsc-Black.otf` file is 17.3 MB. Filtering only used glyphs become necessary, which means more maintenance.
* There may not be free font to choose for other scripts.

## Rationale and alternatives

For Simplified Chinese I've also compared with keeping a serif font. But the uneven thickness is too different from "Alfa Slab One" to look good.

<img width="880" alt="Screenshot 2019-06-11 at 24 47 00-fs8" src="https://user-images.githubusercontent.com/103023/59226544-ccc99980-8c05-11e9-99d6-c90d67934f34.png">

## Maintenance

If we only extract the necessary glyphs from the whole font, we will need to recreate the web font files every time the translation is updated.

* Or we could simply use the [Google Font style sheet](https://fonts.googleapis.com/css?family=Noto+Sans+SC:900&display=swap&subset=chinese-simplified), which has nicely split the font into 119 parts. Though since we're talking about China and Google, there's always a small risk this becomes inaccessible.

## Unresolved Questions

Since "Alfa Slab One" only supports Latin script we still need to find compatible fonts for other scripts. Comparing with the old website, we'll further need fonts for:

- [ ] Japanese
- [ ] Korean 
- [ ] Cyrillic (Russian)

**Comment by skade** [comment] 2019-06-11 07:13
> Or we could simply use the Google Font style sheet, which has nicely split the font into 119 parts. Though since we're talking about China and Google, there's always a small risk this becomes inaccessible.

We can recreate the stylesheet and cut out 119 fonts ourselves. That at least keeps the process stable.

**Comment by tigercosmos** [comment] 2019-07-04 03:57
I think `zh-TW` encounters the same issue.

**Comment by irvin** [comment] 2019-07-04 04:05
If we don't go with custom font for non-western locale, at least we can allocate sans-serif as fallback?

**Comment by skade** [comment] 2019-07-04 16:58
@irvin I would actually like to go with a different font, we mainly need patches for reworking all the fonts.

**Comment by XAMPPRocky** [comment] 2020-03-01 11:09
I'm going to close this a duplicate of #867 as anything new should also consider how it looks in chinese locales.

**Closed by XAMPPRocky** 2020-03-01 11:09 UTC
Labels: A-Typography, A-i18n, C-Bug
