### ISSUE TITLE
Member list for reference team has duplicate members

### ISSUE THREAD

**Issue by nagisa** [rust-lang/www.rust-lang.org#669] opened 2018-12-27 22:58 UTC
# Content Bug Report

## Page(s) Affected

* [Havvy is listed twice as a reference team member](https://www.rust-lang.org/governance/teams/documentation);

## What needs to be fixed?

N/A

## Suggested Improvement

N/A

**Comment by yoshuawuyts** [comment] 2018-12-31 12:52
Thanks for reporting! -- duplicate of https://github.com/rust-lang/www.rust-lang.org/issues/659

**Closed by yoshuawuyts** 2018-12-31 12:52 UTC
Labels: duplicate
