### ISSUE TITLE
install page shows 404

### ISSUE THREAD

**Issue by Dmitry-Borodin** [rust-lang/www.rust-lang.org#625] opened 2018-12-10 11:50 UTC
https://www.rust-lang.org/install.html
This link provided from [The book](https://doc.rust-lang.org/book/ch01-01-installation.html) and google -  leads to 404 error, instead of showing the link to download and install the package.

**Comment by dmm** [comment] 2018-12-10 16:37
The install url changed and a redirect wasn't added to the old url. A google search for "install rust" also returns a 404 page: https://www.rust-lang.org/en-US/install.html.

A fix would be to add 301 redirects from all of the old urls to the new ones.

**Comment by mbrubeck** [comment] 2018-12-10 18:14
Duplicate of #593. This will be fixed by #597.

**Comment by nrc** [comment] 2018-12-11 01:13
Closing as dup of #593

**Closed by nrc** 2018-12-11 01:13 UTC
