### ISSUE TITLE
Add a flat list of next events 

### ISSUE THREAD

**Issue by Mannshoch** [rust-lang/www.rust-lang.org#928] opened 2019-10-03 12:39 UTC
# Design Feature Request
## Summary
Embeding the Calendar is a nice tool. But it does not look good If you have only on event per Month. In such case It would be better to have a flat list of the next events.

_Lower Priority:_ 
Also there is a need for a Link addition to choose the Calendar appearance. 

e.g actual.
https://EXAMPLE.COM/index.php/apps/calendar/embed/123456789abc
shows a Monthly calendar (could be changed to Day and Week on Menu)

e.g. new.
https://EXAMPLE.COM/index.php/apps/calendar/embed/123456789abc#FlatList
or
https://EXAMPLE.COM/index.php/apps/calendar/embed/123456789abc/FlatList

I would suggest:
#FlatList - A Flat list of the next Events (lazy load new events)
#Month - Month View as current available
#7Day - Week View as current available
#[x]Day - Configuratable count of Days in a Row (like week view)
#Day - Day View as current available

_Far in future:_
May I could be able to create a custom css file with my own design
#Day-OWN_DESIGN
#Week-OWN_DESIGN
#Month-OWN_DESIGN

## Motivation
I wish to embed this into a Website and replace the google calendar. But I only get the permission if I get a list view.

## Drawbacks
Design problems?

## Rationale and alternatives
- List of Date is easy to read especially if you do not have that much per month
- Linking the view into the embedding link allows a flexible way to modify the appearance even you have no access to the cloud itself
- I could not replace the Google Calendar without this.

## Maintenance
- The Flat List view: by nextcloud/calendar
- The change on the embedding Link: by nextcloud/calendar
- The own Design: by the server maintainer

## Unresolved Questions
- Embedd a specific event and show it's description 
- Description may in MarkDown / HTML
- Click on location and Nextcloud/Map open https://github.com/nextcloud/maps
- Click on attachment and Nextcloud/files https://github.com/nextcloud/calendar/issues/298 or https://github.com/nextcloud/calendar/issues/1504 open
- Click on nextcloud/polls viewed in calendar and subscribe to it https://github.com/nextcloud/polls/issues/411

**Comment by XAMPPRocky** [comment] 2020-03-01 10:38
I'm going to close this as duplicate of https://github.com/rust-lang/www.rust-lang.org/issues/283 moving calendar systems is something that is more of issue for the Rust project in general rather than the website specifically.

**Closed by XAMPPRocky** 2020-03-01 10:38 UTC
Labels: C-Enhancement
