### ISSUE TITLE
Code blocks in "get started" examples ignore line breaks

### ISSUE THREAD

**Issue by clayheaton** [rust-lang/www.rust-lang.org#933] opened 2019-10-14 18:38 UTC
# Design Bug Report

## Page(s) Affected
https://www.rust-lang.org/learn/get-started

## What needs to be fixed?
The code examples are formatted incorrectly. Line breaks in the code blocks are ignored. 

Here's an example screenshot from the page mentioned above, taken on Chrome on MacOS on 14 October 2019.

![Screen Shot 2019-10-14 at 2 33 11 PM](https://user-images.githubusercontent.com/205364/66774679-2978e180-ee90-11e9-8e6e-971e09ff3124.png)

**Comment by wezm** [comment] 2019-10-15 05:56
I think this is a duplicate of #926 which should be fixed by #932.

**Comment by JohnTitor** [comment] 2019-12-26 07:47
This is fixed on the latest deployment, can be closed.

**Closed** 2019-12-27 08:13 UTC
