### ISSUE TITLE
Link forge from the website

### ISSUE THREAD

**Issue by spastorino** [rust-lang/www.rust-lang.org#843] opened 2019-05-30 21:19 UTC
Forge has a lot of documented procedures that are very handy. Would be great to link it somewhere from the main site. I guess somewhere in the community section.

/cc @nikomatsakis

**Comment by nikomatsakis** [comment] 2019-05-31 20:39
I'm not sure where, but it's definitely true that many contributors have no idea forge exists

**Comment by skade** [comment] 2019-06-03 07:58
The planned Contribution page (https://github.com/rust-lang/www.rust-lang.org/issues/440) would be a good place.

**Comment by XAMPPRocky** [comment] 2020-03-01 11:14
Going to close this as a duplicate of #440

**Closed by XAMPPRocky** 2020-03-01 11:14 UTC
Labels: A-Content, C-Enhancement
