### ISSUE TITLE
#infra discord channel seems to have been moved 

### ISSUE THREAD

**Issue by Lectem** [rust-lang/www.rust-lang.org#1205] opened 2020-07-23 19:43 UTC
### What needs to be fixed?

The #infra discord channel is mentioned as a way to get in touch with the infrastructure team but does not exist anymore. 
According to some discord members it has been moved to Zulip. 

### Page(s) Affected

https://www.rust-lang.org/governance/teams/operations#infra

**Comment by XAMPPRocky** [comment] 2020-07-23 21:15
Thank you for your issue! Yes that is correct, I'm going to close this as a duplicate of #1190 as it is the same problem. Removing the discord link is done over at https://github.com/rust-lang/team/blob/master/teams/infra.toml

**Closed** 2020-07-23 21:15 UTC
Labels: A-Content, C-Bug
