### ISSUE TITLE
Do not parse filename into `String` in CLI example

### ISSUE THREAD

**Issue by nagisa** [rust-lang/www.rust-lang.org#917] opened 2019-08-19 13:56 UTC
# Content Bug Report

## Page(s) Affected

https://www.rust-lang.org/what/cli

## What needs to be fixed?

The example that currently reads like this:

```
/// Read some lines of a file
#[derive(Debug, StructOpt)]
struct Cli {
    /// Input file to read
    file: String,
    /// Number of lines to read
    #[structopt(short = "n")]
    num: usize,
}
```

## Suggested Improvement

`file` should be `PathBuf` or `OsString`.

**Comment by tshepang** [comment] 2019-08-19 16:59
I'd go as far as calling the binding `path`, for I like reserving the name `file` for the handle itself (`let file = File::open...`)

**Comment by XAMPPRocky** [comment] 2020-03-01 10:42
I'm going to close this as duplicate of #838

**Closed by XAMPPRocky** 2020-03-01 10:42 UTC
Labels: A-Content, C-Enhancement
