### ISSUE TITLE
The landing page doesn't tell the visitor what rust is

### ISSUE THREAD

**Issue by JakeTherston** [rust-lang/www.rust-lang.org#754] opened 2019-05-08 01:59 UTC
# Content Bug Report

## Page(s) Affected
The landing page.

## What needs to be fixed?
The landing page never states that Rust is a programming language. In fact, the term "programming language" is never stated once. In it's current state, a visitor can not be reasonably expected to understand what Rust from the landing page.

## Suggested Improvement
Add "Rust is a programming language that..." above the fold.

**Comment by skade** [comment] 2019-05-08 11:15
Thanks for the report <3. It's a duplicate of #612, though.

**Closed by skade** 2019-05-08 11:15 UTC
