### ISSUE TITLE
"Getting started" and "Install Rust" don't mention that Linux users need a linker

### ISSUE THREAD

**Issue by skierpage** [rust-lang/www.rust-lang.org#1652] opened 2022-03-11 04:04 UTC
### What needs to be fixed?
I returned to building rust programs on Fedora 35, ran `rustup update`, and re-read Getting started. I ran straight into `error: linker `cc` not found`. If you Google this seems to be an extremely common problem, you need to install gcc, or build-essentials, or whatever (I must have uninstalled the linker in the interim.) But there is no mention of this in the official docs.

### Page(s) Affected
https://www.rust-lang.org/learn/get-started
https://www.rust-lang.org/tools/install

### Suggested Improvement
Something like:
> rustup installs the Rust compiler and several other tools, but on Linux you will need to install a linker program.

On Fedora, I think the minimal install is `sudo dnf install gcc`.

**Comment by senekor** [comment] 2024-05-23 18:31
duplicate of https://github.com/rust-lang/www.rust-lang.org/issues/1379

**Closed** 2024-05-23 18:32 UTC
Labels: C-Bug, A-Content
