### ISSUE TITLE
blog.rust-lang.org is broken

### ISSUE THREAD

**Issue by danilaml** [rust-lang/www.rust-lang.org#615] opened 2018-12-08 13:32 UTC
# Design Feature Request
## Summary
blog.rust-lang.org is negatively impacted by the "new" design". Lot's of missing features, broken images and etc.

## Motivation
New design is a significant downgrade. It looks worse, the font is hard to read, the colors are bad, and it also broke all the images in the old articles.

Here is the example of what I'm talking about:

![image](https://user-images.githubusercontent.com/2046350/49686454-e6c6da00-fb05-11e8-924c-33c4be3b9f2d.png)

It also spews a bunch of `/fonts/FiraSans-*.ttf:1 Failed to load resource: the server responded with a status of 404 ()` errors into the console.

Furthermore, it's missing syntax highlighting (though I've seen some PRs that indicate that it's coming).

Sorry for a bit of opinionated/unconstructive criticism, but there is no other outlet to report the issue and I'm just really frustrated why such broken design (it doesn't even look better nor does it contain more info!) was approved without any way to fall back. 

At the moment, the landing page for rust lang looks worse than any other popular language I know (and tried).
Thanks for your attention. I hope it'll be resolved.

**Comment by ashleygwilliams** [comment] 2018-12-08 15:48
hi: a couple of things:

1. this issue is unecessarily harsh and cruel. as a result i am going to close it.
2. it contains multiple duplicate of previous filed and then solved issues.
3. it is filed on the wrong repo (this is the website, not the blog repo).

i am closing this due to the first point but the others are also true. i do think there are pieces of good information in this issue. i would encrouage you to rethink how you are expressing your thoughts and refile, smaller, more actionable issues, after reviewing the current tracker. if you'd like to give feedback on the website, you can file here. for the blog please file on the blog.rust-lang.org repo.

**Closed by ashleygwilliams** 2018-12-08 15:48 UTC

**Comment by danilaml** [comment] 2018-12-08 16:41
@ashleygwilliams no problem. My frustration just seeped in into my report making it less useful. The insanity of the last few years made pointless redesigns that destroy the software/product I use, a significant pain point of mine.
The only information I've found at first cam from https://blog.rust-lang.org/2018/11/29/a-new-look-for-rust-lang-org.html article and I assumed that this redesign is shared among *.rust-lang.org and as such should be reported in the single given place. Perhaps, a simple update/edit to the end of the article clarifying that all official rust-related websites will/did undergo the redesign and that issues should be reported to each respective project, but that's just a nitpick at this point.

Perhaps, this "report" of mine would be better suited for some angry reddit post, but it so happens I don't really browse /r/rust and this change has caught me off-guard. I'm sure it'll all be resolved in due time, so best wishes with that and again forgive me for being unhelpful.
