### ISSUE TITLE
Hard to select inline code samples

### ISSUE THREAD

**Issue by j-delaney** [rust-lang/www.rust-lang.org#1047] opened 2020-03-28 12:31 UTC
### Page(s) Affected
https://www.rust-lang.org/learn/get-started

### What needs to be fixed?
Selecting inline code samples is hard to do and often accidentally selects non-code text:

![Mar-28-2020 12-23-17](https://user-images.githubusercontent.com/3589480/77822915-00bb7000-70ef-11ea-99f2-3ce66fffad4d.gif)

### Suggested Improvement
I think there are two main ways to fix this. The first is to have code samples that users will be selecting often be on their own line. This is done on some sections and makes it easy to select the code:
<img width="1152" alt="Screen Shot 2020-03-28 at 12 29 32 PM" src="https://user-images.githubusercontent.com/3589480/77823019-d5855080-70ef-11ea-93f2-3efeca75a9b7.png">

The second way would be to add the `user-select: all` CSS property to `code` tags ([docs](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select)). This would allow users to just single-click on the code to select it:
![Mar-28-2020 12-26-04](https://user-images.githubusercontent.com/3589480/77822964-51cb6400-70ef-11ea-9703-0883051d0e48.gif)

The downside of this would be potentially unexpected selection behavior for users (I'm not sure how familiar users are with this form of text selection). For example, drag-and-select behaves oddly (at least in Chrome) when this property is set to `all`:
![Mar-28-2020 12-27-02](https://user-images.githubusercontent.com/3589480/77822974-7a535e00-70ef-11ea-9fce-f5ebd0bad0b1.gif)

I think the first method is preferred since it doesn't introduce behavior that might confuse users.

I'm happy to open a PR to implement whatever fix you all think is best!

**Comment by XAMPPRocky** [comment] 2020-03-28 17:00
Thank you for your issue! I would prefer the second approach as a short term solution, as I'm not a fan of the current plain code block styling on it's own, and later try address later code block styling as a whole.

**Comment by j-delaney** [comment] 2020-03-28 17:17
@XAMPPRocky 
Looking into it a bit more, is this section even needed anymore? I'm new to Rust and when I followed the guide on this page it installed `clippy` and `rustfmt` by default (according to https://github.com/rust-lang/rustup this is expected and normal behavior). In that case, should this section just be there to mention that, by following this guide, Rust comes with a formatter and linter?

**Comment by XAMPPRocky** [comment] 2020-03-29 09:02
@j-delaney I've address that now in #1048 removing the text. We already feature those tools on the tools page. I'm not sure where that text was would be a good place to say "hey there's a formatter and linter". I think if anything I think they should have a small section on their own in "Get Started", showing their usage rather than just saying they exist.

**Comment by senekor** [comment] 2024-05-23 18:41
The specific section recorded here doesn't exist anymore. For the other inline code blocks, I was unable to reproduce the issue. Selecting works fine for me.

I'm going to tentatively close this, but please feel free to ping me if this is still an issue for you. It might be a browser difference. (I tested with firefox and chromium.)

**Closed by senekor** 2024-05-23 18:41 UTC
Labels: C-Enhancement, A-Design, P-Get-Started
