### ISSUE TITLE
Bad kerning on double f in slogan on Chrome/Linux

### ISSUE THREAD

**Issue by IsaacWoods** [rust-lang/www.rust-lang.org#590] opened 2018-12-07 09:43 UTC
(Sorry for not following the issue template quite - maybe a template for small style issues like this would suit better?)

# Design Feature Request
## Summary
The slogan doesn't render brilliantly on Chrome 66. I assume this is because it tries to ligature the `fi`, which makes the second `f` appear lower and too close to the first.
![rust bad kerning](https://user-images.githubusercontent.com/10314464/49639985-4046e000-fa04-11e8-959d-17412a1e8895.png)

## Motivation
The slogan is pretty front-and-center in the new design, and one of the first things new users will read. I don't think poor kerning represents our commitment to quality well, and detracts from what is otherwise a clean design.

## Drawbacks
I am not a webdev and have no idea how this problem should be solved, but I don't see any drawbacks if this is possible.

## Rationale and alternatives
n/a

## Maintenance
n/a

## Unresolved Questions
n/a

**Comment by Maxgy** [comment] 2018-12-07 13:42
Both my phone and PC have two perfectly aligned 'f's.  Is this still a problem for you?

**Comment by ashleygwilliams** [comment] 2018-12-07 14:12
This is very interesting- thank you for filing @IsaacWoods ! Could you give us some more information on the browser you viewed this issue in?

**Comment by chriskrycho** [comment] 2018-12-07 14:58
Chrome 66 on what OS, specifically? There's actually an "ffi" ligature in the font which *should* be rendered in any Chrome version since… a long time ago, well before 66. 🤔

**Comment by IsaacWoods** [comment] 2018-12-07 15:53
Chrome on up-to-date Fedora 28, specifically. I've also just checked on Firefox on the same machine and it renders correctly, so this looks like a Chrome-specific issue.

The contents of `chrome://version`:
```
Google Chrome: 66.0.3359.139 (Official Build) (64-bit)
Revision: a020eddf0d85fe84d4a6787b304f50aafb670969-refs/branch-heads/3359@{#767}
OS: Linux
JavaScript: V8 6.6.346.26
Flash: 32.0.0.101 /home/isaac/.config/google-chrome/PepperFlash/32.0.0.101/libpepflashplayer.so
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
Command Line: /usr/bin/google-chrome-stable --password-store=gnome --flag-switches-begin --ignore-gpu-blacklist --flag-switches-end
Executable Path: /opt/google/chrome/google-chrome
Profile Path: /home/isaac/.config/google-chrome/Default
Variations: c134752e-5521195f419cc9-ca7d8d8059aeb88e-3f4a17df3095aa95-3f4a17df7c1bc906-f55a7974d52c4ff7-d52c4ff747e5d3db-3d47f4f44dc30737-b8a5ea08589b4e9f-3f4a17dff9884634-659882c0ceff87ec-3f4a17df5485fc4d-ca7d8d80ef05a96e-e2c3ac678e3b2dc5-937025906a82868d-3f4a17dfc322f799-2dbe5f9da92f51d-3d47f4f43de1fbf2-3d47f4f4f79cb77b-3d47f4f42b33233e-cc2bd7de2c1d398c-3f4a17df72606c4f-3f4a17df2a32876a-ca7d8d809a2f4e5b-d226bfeb1354da85-f1a864dc494d8760-52325d433ac60855-486e2a9cf296190c-6754d7b74442aae2-6bdfffe7ed1d377-e1cc0f1475f0f0a0-d7f6b13ce2b18481-5c63917ae7e71889-e1cc0f143a8271ac-12c22694e68624-803f8fc4
```

**Comment by nagisa** [comment] 2018-12-27 22:31
> There's actually an "ffi" ligature in the font which should be rendered in any Chrome version since

The ligature may be (and definitely is, on Firefox) disabled by the `letter-spacing: -.1rem` rule.

**Comment by bungeman** [comment] 2019-02-06 22:59
Chrome 73 has a change to make non-default letter-spacing disable optional ligatures (as well as some other ligature related fixes), which explains why things are 'fixed' in Chrome 73. The font is FiraSans, and it is likely that the issue seen is due to auto hinting, since I can reproduce on Chrome 72 by changing my system settings to 'slight' hinting. I believe the FreeType auto hinter should figure out that this glyph is a ligature using HarfBuzz and apply the appropriate blue zones, but for some reason this didn't happen correctly. Also, the particular FiraSans served up as a webfont here does not have an 'ffi' ligature, just 'fi' and 'fl'. It may be interesting to see if these issues are fixed in FiraGo, the successor to FiraSans.

**Comment by yoshuawuyts** [comment] 2019-02-13 09:54
@bungeman thanks for the thorough writeup! Do you have any recommendations where to go from here?

**Comment by bungeman** [comment] 2019-02-13 16:00
I'm not entirely sure. If I set my system settings to autohinting, load the page in question in Firefox, and then turn off the letter-spacing using the inspector (so that the ligatures can apply) I get the same odd autohinting result. Note that this issue is discussed at length (and originally fixed!) at https://bugzilla.redhat.com/show_bug.cgi?id=368561 . It appears the reason FreeType cannot hint this particular ligature is due to the font missing cmap entries for U+FB00 through U+FB06 to point at these glyphs. So Chrome 73 will 'fix' this, but you could also try FiraGo which does have at least U+FB01 and U+FB02 mapped, so should avoid this issue. Or, for minimal changes you could add these mappings to the existing font using FontTools ttx.

**Comment by skade** [comment] 2019-05-09 22:21
Is there an estimate how prevalent this issue is? I would like to avoid fixes for something that is clearly a bug some browsers rendering.

I don't experience this issue with Fedora 29 and Chrome 73 (as expected).

That said, FiraGO might be a good choice in the future because of better support non-latin scripts.

**Comment by skade** [comment] 2019-05-10 08:53
I decided to close this as a fringe subject that I can't judge. If you think I misjudge the impact of this problem, please ping me and reopen.

Thanks for the awesome research and I will take the suggestion of going for FiraGO!

https://github.com/rust-lang/www.rust-lang.org/issues/755

**Closed by skade** 2019-05-10 08:53 UTC
Labels: OS-specific: linux, browser-specific: chrome, bug, design, waiting on response
