### ISSUE TITLE
"Looking for the previous website?" link goes to 404

### ISSUE THREAD

**Issue by jeremy-w** [rust-lang/www.rust-lang.org#577] opened 2018-12-06 19:46 UTC
# Technical Bug Report
## Your Environment
| Software         | Version(s) |
| ---------------- | ---------- |
| Form Factor      | Desktop |
| Browser Type     | all |
| Browser Version  | latest |

## Is this an issue with Rust, CSS, or HTML (or a combination)?
I guess HTML, but suspect the fix is not going to involve fixing the HTML, but some GitHub config.

## Expected Behavior
When I click "previous website?", I see the previous website.

## Current Behavior
I visit https://prev.rust-lang.org/
I see the GitHub Pages 404

![screen shot 2018-12-06 at 14 44 21](https://user-images.githubusercontent.com/29010/49607967-75502580-f965-11e8-8b1d-970a28a7f614.png)

## Step to Reproduce
Please provide the steps to reproduce the issue.

- visit https://www.rust-lang.org/
- scroll to bottom
- click "previous website?"

## Screenshots
If relevant, please include screenshots of the issue you are seeing.

repro gif
![rust - dead link to prev website](https://user-images.githubusercontent.com/29010/49608063-b47e7680-f965-11e8-8358-5cf880f4ab4e.gif)

**Comment by ashleygwilliams** [comment] 2018-12-06 20:06
good catch. i believe this was caused by me renaming the previous site's repo. thank you for the comprehensive issue- i'm working to fix it right now!

**Comment by ashleygwilliams** [comment] 2018-12-06 22:20
this has been fixed now! thank you so much for filing!

**Closed by ashleygwilliams** 2018-12-06 22:20 UTC
Labels: bug, ops
