### ISSUE TITLE
A small rust application code isn't working

### ISSUE THREAD

**Issue by Hamza12700** [rust-lang/www.rust-lang.org#1855] opened 2023-08-17 18:25 UTC
### Problem
In [Getting Starting Page](https://www.rust-lang.org/learn/get-started) **A small rust application** code isn't working! The `message` variable has a mismatched type `mismatched types expected &str found &[u8]`.
![20230817_11h22m12s_grim](https://github.com/rust-lang/www.rust-lang.org/assets/72913359/edd427f4-3a5e-401c-a5fb-594de0321bfe)
![20230817_11h23m21s_grim](https://github.com/rust-lang/www.rust-lang.org/assets/72913359/44c9203f-b953-4432-a7bf-96dc5ff3c4a1)

### Suggested Improvement
Instead of this:
```rust
let message = String::from("Hello fellow Rustaceans!");
```
Just simply do this:
```rust
let message = "Hellow fellow Rustaceans!";
```

**Comment by senekor** [comment] 2023-08-17 18:43
I think this is a duplicate of https://github.com/rust-lang/www.rust-lang.org/issues/1847.

Note the version of the crate `ferris_says` on the website is out of date, it uses `0.2`. This is stated in the instructions though.

The example was updated to use the newer version, but that isn't deployed yet.

**Closed** 2023-08-17 19:56 UTC
Labels: C-Bug, A-Content
